In [1]:
import nltk
import numpy as np
import pandas as pd

filepath_dict = { 'v4 - Copy1.txt'}
df_list = []
  
for filepath in filepath_dict:
    df = pd.read_csv(filepath, names=['sentence', 'label'], sep='\t')
#     df['source'] = source 
    df_list.append(df)

df = pd.concat(df_list)
print(df)

                                              sentence  label
0    ورزش  به تمامی گونه‌های فعالیت فیزیکی بدن گفته...      0
1    و سازمان یافته یا گاه به گاه در آن شرکت کنند و...      0
2    ورزش به فعالیتها یا مهارتهای عادی جسمانی‌ای گف...      0
3    برای مسابقه، نشاط شخصی، دستیابی به ورزیدگی، مه...      0
4    به تاریخچه کامل آنها به ما مطالب مهمی درباره ت...      0
..                                                 ...    ...
110  به عبارت دیگر، هدف تاریخ علاوه بر اینکه معرفت ...      2
111   نظیر امور اقتصادی، مذهبی، سیاسی، هنری، حقوقی،...      2
112   با این حال می‌توان آن را به عنوان پلی بین این...      2
113  تاریخ‌نگاران از گذشته کوشیده‌اند تا پرسش‌های ت...      2
114   با این‌حال پژوهش‌های تاریخی تنها به این منابع...      2

[115 rows x 2 columns]


In [6]:
from __future__ import unicode_literals
from hazm import *
normalizer = Normalizer()
st=[]
s=[]


for i in df.sentence.values:
   normalizer.normalize(i)

tokenize=[]
for i in df.sentence.values:
       tokenize.append(word_tokenize(i))
# print(tokenize)
stemmer = Stemmer() 
for i in tokenize:
    for j in i:
          st.append(stemmer.stem(j))
    
# print(st)
lemmatizer = Lemmatizer()
l=[]

for i in st:
        l.append(lemmatizer.lemmatize(i))
print(l)

['ورز', 'به', 'تمام', 'گونه', 'فعال', 'فیزیک', 'بدن', 'گفت#گو', 'که', 'شرک', 'کنندگ', 'آن', 'توانست#توان', 'به', 'صور', 'منظ', 'و', 'ساز', 'یافته', 'یا', 'گاه', 'به', 'گاه', 'در', 'آن', 'شرک', 'کرد#کن', 'و', 'از', 'آن', 'برا', 'بهبود', 'تناسب', 'اندام', 'یا', 'فراه', 'آوردن', 'سرگرم', 'و', 'تفریح', 'بهره', 'ببرند', '.', 'ورز', 'به', 'فعالیت', 'یا', 'مهارت', 'عاد', 'جسمانی', 'گفت#گو', 'که', 'بر', 'پایه', 'یک', 'رشته', 'قوانین', 'مورد', 'توافق', 'همگان', 'و', 'با', 'اهداف', 'تفریح', '،', 'یا', 'برا', 'مسابقه', '،', 'نشاط', 'شخص', '،', 'دستیاب', 'به', 'ورزیدگ', '،', 'مهار', 'جو', 'یا', 'آمیزه', 'از', 'این', 'اهداف', 'انجا', 'گرفت#گیر', '.', 'توسعه', 'ورزش', 'با', 'توجه', 'به', 'تاریخچه', 'کامل', 'آن', 'به', 'ما', 'مطالب', 'مهم', 'درباره', 'تغییر', 'اجتماع', 'و', 'همچنین', 'به', 'مقدار', 'زیاد', 'درباره', 'خود', 'ورزش', 'آموخت#آموز', '.', 'کشف', 'بسیار', 'مدرن', 'در', 'فرانسه', '،', 'افریقا', 'و', 'استرالیا', 'درباره', 'هنر', 'غارنشین', 'وجود', 'داشت#دار', '(', 'برا', 'مثال', 'لاسکائوکس', 

In [7]:
import nltk
import numpy as np
# nltk.download('punkt')

stopword = open('stopword.txt', 'r', encoding='utf-8').read()

clean_sentence = [w for w in l if(not (w in stopword))]
for i in clean_sentence:
    n=i
    i = i.replace('\u200c', '')
    clean_sentence[clean_sentence.index(n)] = i
# print(int(y.shape))
print(clean_sentence)
o1=[]
o = []
y = df.label.values
for j in range(y.shape[0]):
          o1 = ' '.join(clean_sentence[:20])
          for i in clean_sentence[:20]:
              clean_sentence.remove(i)
          o.append(o1)  

['ورز', 'فعال', 'فیزیک', 'بدن', 'گفت#گو', 'شرک', 'کنندگ', 'توانست#توان', 'منظ', 'شرک', 'کرد#کن', 'بهبود', 'تناسب', 'اندام', 'فراه', 'سرگرم', 'تفریح', 'بهره', 'ببرند', 'ورز', 'فعالیت', 'مهارت', 'عاد', 'جسمانی', 'گفت#گو', 'پایه', 'قوانین', 'توافق', 'اهداف', 'تفریح', 'مسابقه', 'نشاط', 'دستیاب', 'ورزیدگ', 'مهار', 'آمیزه', 'اهداف', 'گرفت#گیر', 'توسعه', 'ورزش', 'توجه', 'تاریخچه', 'مطالب', 'مهم', 'تغییر', 'اجتماع', 'ورزش', 'آموخت#آموز', 'کشف', 'مدرن', 'فرانسه', 'افریقا', 'استرالیا', 'هنر', 'غارنشین', 'داشت#دار', 'مثال', 'لاسکائوکس', 'ماقبل', 'تاریخ', 'ببینید', 'شواهد', 'جشن', 'غیره', 'داد#ده', 'ازتاریخ', 'منابع', '۳۰۰۰۰', 'مربوط', 'شد#شو', 'تاریخ', 'نویس', 'کربن', 'ثب', 'شد#شو', 'شواهد', 'کاف', 'ورز', 'منابع', 'داشت#دار', 'تصور', 'فعالیت', 'دور', 'معادل', 'تعریف', 'ورز', 'ورز', 'دانست#دان', 'منظور', 'چابک', 'بدن', 'ایجاد', 'قوّ', 'پاروزن', 'بوکس', 'کشت', 'شمشیرزن', 'تیرانداز', 'اسک', 'ورز', 'ساف', 'بسکتبال', 'انواع', 'فوتبال', 'چوگ', 'والیبال', 'گلف', 'انواع', 'تنیس', 'پرتاب', 'وزنه', 'جزو', 

In [9]:
from sklearn.model_selection import train_test_split

sentences_train, sentences_test, y_train, y_test = train_test_split(
    o, y, test_size=0.25, random_state=0)
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit(sentences_train)

X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
print('vec X_train: \n', X_train.toarray())
print('\n')

print('vec X_test: \n',X_test.toarray())


vec X_train: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


vec X_test: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
from sklearn.neural_network import MLPClassifier
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

mlpclassifier = MLPClassifier(random_state=1,hidden_layer_sizes=(100))
mlpclassifier.fit(X_train, y_train)

print("Accuracy: %.2f" %mlpclassifier.score(X_test, y_test))

Accuracy: 0.79
